INSERT INTO `system` (`id`, `name`, `display_name`, `value`, `field_type`, `comment`, `timestamp`, `reseller_id`, `is_display`, `group_title`, `sub_group`) VALUES
(NULL,'other_payment_gateway_fees','Other Payment Gateway Taxes','50','default_system_input','Set other payment gateway taxes',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'sandbox_statusrequestAPI','Sandbox Statusrequest API ','http://demo.pesapal.com/api/QueryPaymentDetails','default_system_input','Please enter statusrequest API for sandbox ',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'live_statusrequestAPI','Live Statusrequest API','http://demo.pesapal.com/api/QueryPaymentDetails','default_system_input','Please enter statusrequest API for Live',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'sandbox_consumer_key','Sandbox Consumer Key','uO41/bISvsr9xTnIO9zMzW6C+VFkLXPs','default_system_input','set pesapal sandbox consumer key',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'live_consumer_key','Live Consumer Key','Sqbeqbtki6866dvlEEAxv8g4boSRFvQa','default_system_input','set pesapal live consumer key',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'sandbox_consumer_secret','Sandbox Consumer Secret','MYz2SetB1wVQFdcZj/VPZLYQYGg=','default_system_input','Set pesapal sandbox Consumer Secret',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'live_consumer_secret','Live Consumer Secret','R9vnAepl8uDuSeXi/sIQn8+w9Ow=','default_system_input','Set pesapal live Consumer Secret',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'sandbox_iframelink','Sandbox iframelink','http://demo.pesapal.com/api/PostPesapalDirectOrderV4','default_system_input','Set pesapal sandbox iframelink url',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'live_iframelink','Live iframelink','https://www.pesapal.com/API/PostPesapalDirectOrderV4','default_system_input','Set pesapal live iframelink url',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'description','Description','Please enter description for invoice.','default_system_input','Set description for invoice.',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'pesapal_amount','Pesapal Minimum Amount','0','default_system_input','Minimum amount of recharge',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'pesapal_tax','Pesapal Tax','0.5','default_system_input','Set pesapal tax rate (in percentage) apply to recharge amount',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'pesapal_fee','Pesapal Fee','1','enable_disable_option','Set who should pay pesapal fee',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'pesapal_mode','Pesapal Mode','1','paypal_mode','Set pesapal mode. Sandbox for testing',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'pesapal_sandbox_id','Pesapal Sandbox Id','pesapal@test.com','default_system_input','Set pesapal sandbox account id for testing',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'pesapal_id','Pesapal Id','billing@elige-africa.com','default_system_input','Set pesapal live account id',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'pesapal_sandbox_url','Pesapal Sandbox Url','https://www.sandbox.pesapal.com/cgi-bin/webscr','default_system_input','Set pesapal sandbox url for testing',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'pesapal_url','Pesapal Url','https://www.pesapal.com/cgi-bin/webscr','default_system_input','Set pesapal live url',NULL,0,0,'pesapal-mpesa','pesapal-mpesa'),
(NULL,'pesapal_status','Pesapal','0','enable_disable_option','Set enable to add pesapal as payment gateway option',NULL,0,0,'pesapal-mpesa','pesapal-mpesa');
